trigger:
- release/rocm-rel-6.0

pool: NV31

steps:
- script: |
    mkdir build

- script: |
     ./install.sh -c
  displayName: "Building rocFFT with the install script"

- script: |
    cd build
    ls
    ./rccl-UnitTests
  displayName: "CDing into build directory"

