trigger:
- release/rocm-rel-6.0

pool: NV31

steps:
- script: |
    mkdir build

- script: |
    echo "rocm" | sudo -S ./install.sh -i -c -d
  displayName: "Building rocFFT with the install script"

- script: |
    cd build
    ls
    ./rccl-UnitTests
  displayName: "CDing into build directory"


